version: '3.3' #apt install docker-compose didn't like version 3.8

services:
  web:
    build:
      context: .
    ports:
    - 5000:5000
    environment:
    - DATABASE_URL=INSERT_LATER
    volumes:
    - ./:/app

  