# syntax=docker/dockerfile:1

FROM node:18-bullseye

WORKDIR /frontend

COPY frontendV2/ ./

RUN npm install

RUN npm run build

FROM golang:alpine

WORKDIR /backend

COPY main.go go.sum go.mod ./

COPY models/ models/

COPY mongoUtil/ mongoUtil/

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build

# this last bit reduces the image size from over a gigabyte to about 20 megabytes
FROM alpine:latest

WORKDIR /app

COPY --from=0 /frontend/public ./frontendV2/public

COPY --from=1 /backend/funholidaysapi ./

COPY --from=1 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY doc.md ./

ENV PORT 5000

ENV MONGOURI "must-be-set"

ENV HOLIDAYCOLLECTIONNAME "holidays"

ENV MONGODBNAME "go-holiday-api"

CMD [ "./funholidaysapi" ]